### ISSUE TITLE
Run duration not represented correctly in Azure Pipelines

### ISSUE THREAD

**Issue by AndrewCraswell** [ShuiRuTian/playwright-trx-reporter#7]
The `Run duration` value is not being shown correctly within the Azure Pipelines test reports. The total duration of my test run was around `5m` but ADO is showing `1s 657ms`:

![image](https://user-images.githubusercontent.com/1908292/221439450-10ddc30a-06ca-4b6f-adf4-2cf05de89836.png)

Here is my `.trx`:

```xml
<Times creation="2023-02-25T12:09:09.095Z" finish="2023-02-25T12:16:03.584Z"/>
```

However, I've investigated another pipeline from our backend team working on a .NET service, and the values from their `.trx` files are showing the proper `Run duration`. Here is an extract from their `.trx`:

```xml
<Times creation="2023-02-25T02:12:15.3185224+00:00" queuing="2023-02-25T02:12:15.3185226+00:00" start="2023-02-25T02:12:11.2045629+00:00" finish="2023-02-25T02:12:22.8210764+00:00" />
```

My guess is ADO is trying to use the `start` and `finish` times to calculate the duration, but `playwright-trx-reporter` is only recording `creation` and `finish`?

**Comment by ShuiRuTian** [comment]
Oops, your gusses is 100% right:

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2?view=azure-pipelines&tabs=trx%2Ctrxattachments%2Cyaml#result-formats-mapping

I remembered I checked the result once according to the mapping. Maybe it's changed somehow during some refactoring :-/

However, I do not have much time today, will fix it and check other properties by the mapping again tomorrow.

**Comment by AndrewCraswell** [comment]
After updating to `1.06` this looks to be fixed. I will go ahead and close this. Thank you!

![image](https://user-images.githubusercontent.com/1908292/221981753-2030c95a-0801-4690-b3ec-48846cd4a333.png)
